### ISSUE TITLE
Improvement over conda package?

### ISSUE THREAD

**Issue by PertuyF** [ayaanhossain/ViennaRNA#1]
Dear @ayaanhossain,
In the readme for this Pypi installer, you state that the conda package for ViennaRNA is broken. Could you please tell me more?
As far as I know, the conda package ([from Bioconda](https://bioconda.github.io/recipes/viennarna/README.html)) is working well.

**Comment by ayaanhossain** [comment]
At the time I made this installer, the conda recipe wasn't working for Python 3.8 or 3.9 on some machines. I haven't checked recently, the recipe may have been fixed. At any rate, if you want to just `pip install ViennaRNA`, this package will help.
