### ISSUE TITLE
ViennaRNA License is not MIT

### ISSUE THREAD

**Issue by RaumZeit** [ayaanhossain/ViennaRNA#2]
Hi,
first, thanks for setting up and maintaining the PyPI ViennaRNA Package.

While having the package ready to be installed via pip is quite convenient I suppose, you still need to change the license attribution!

The ViennaRNA Package is not distributed under MIT License but comes with its own license conditions! Please update, such that people do not get confused. I understand that your installer itself may be under MIT license, but the installed software is not. However, I don't know how to best separate the both in the license overview on PyPI. Please have a look into that.

On another note, do yo plan to continue maintaining the PyPI package in the future? If so, you might want to consider watching the [ViennaRNA Github repository](https://github.com/ViennaRNA/ViennaRNA) for new releases.

**Comment by RaumZeit** [comment]
Along with my previous comment on the license, the PyPI package suggests, that you are the author of the ViennaRNA Package, not the maintainer...
You should update your `setup.py` to reflect your actual status, e.g.:
```
setup (
...
    author           = 'ViennaRNA Core Developers',
    author_email     = 'rna@tbi.univie.ac.at',
    maintainer       = 'You',
    maintainer_email = 'your email address',
...
)
```
The same goes with the `url` and `project_urls` fields, which I assume should actually point to the upstream ViennaRNA Package to help people find information and report potential issues of the software.

**Comment by ayaanhossain** [comment]
Thanks for getting in touch. I do want to continue maintaining this installer under MIT, however, I'll update the README to reflect the fact that ViennaRNA comes with its own license.

I do give full credit to TBI and I even mention the paper to be cited for ViennaRNA. However, I did write this installer, without any help from TBI / ViennaRNA Core, so I think I should be listed as the author for this ViennaRNA installer program inside the `setup.py` which is automatically parsed by PyPI.
