### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by wilfriedguiblet** [ayaanhossain/ViennaRNA#5]
Hi,

I am having an issue running an RNAlib function in python. Here is my script:

```
import RNA
seq = "GAGUAGUGGAACCAGGCUAUGUUUGUGACUCGCAGACUAACA" 
md = RNA.md()
fc = RNA.fold_compound(seq, md)
fc.mfe_window_zscore(1)
```

and get the error `Segmentation fault: 11`

Am I doing something wrong or is there an issue?

Note: I am on Mac and using RNAlib 2.5.0.

Thanks!

**Comment by ayaanhossain** [comment]
My my, what are the chances! Nice to see you here Will. I checked your code above, and it indeed crashes with a segfault just like you showed. This is not an issue with the ViennaRNA package installation but with the core C/++ programs, unfortunately -- so beyond my scope to fix this. I'd get in touch with the folks at Vienna and ask them for a resolution, showing this exact example. The core ViennaRNA GitHub is at https://github.com/ViennaRNA/ViennaRNA.

[Looking at the docs](https://www.tbi.univie.ac.at/RNA/ViennaRNA/doc/html/group__mfe__window.html#gaa4f67ae94efd08d800c17f9b53423fd6), my guess is that the underlying C/++ code is having trouble putting stuff out to stdout within python REPL. Besides the z-score threshold, the function requires a file pointer, and in its absence, the function routes the predictions to the standard output which is likely where the segfault is originating from.
